backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: https://fervent-bardeen-0b318e.netlify.app
display_url: https://fervent-bardeen-0b318e.netlify.app
logo_url: https://fervent-bardeen-0b318e.netlify.app/images/logo.svg
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'content/homepage.md'
        preview_path: '/'
        editor:
          preview: false
        fields:
          - {
              label: Title,
              name: title,
              widget: string,
              hint: 'Enter your name or your company name.',
            }
          - {
              label: Intro,
              name: body,
              widget: markdown,
              hint: 'Enter a description about yourself.',
            }
          - {
              label: Photo,
              name: file,
              widget: file,
              default: '/images/uploads/jump.jpg',
              hint: 'Select a photo that will be displayed to fill your screen.',
            }
