backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}'
    update: 'Update {{collection}}'
    delete: 'Delete {{collection}}'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}""'
site_url: https://uphill-coaching.netlify.app
display_url: https://uphill-coaching.netlify.app
media_folder: 'src/client/static/images/uploads'
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dvzdkibo3
    api_key: 969247791821814
public_folder: '/images/uploads'
collections:
  - label: 'Pages'
    name: 'pages'
    editor:
      preview: false
    files:
      - label: 'Homepage'
        name: 'homepage'
        description: 'A description of the homepage'
        file: '/src/client/content/homepage.md'
        preview_path: '/'
        fields:
          - label: Site Title
            name: sitetitle
            widget: string
            hint: 'Enter your name, company name, product name.'
          - {
              label: Photo,
              name: file,
              widget: file,
              default: '/images/uploads/jump.jpg',
              allow_multiple: false,
              hint: 'Select a photo that will be displayed to fill your screen.',
            }
          - label: Photo Description
            name: filedescription
            widget: string
            hint: 'Describe the photo. This text can be displayed in Google and social media search results.'
          - {
              label: Tagline,
              name: tagline,
              widget: markdown,
              hint: 'Enter a short goal, which will be displayed over your selected photo.',
            }
          - {
              label: Intro,
              name: intro,
              widget: markdown,
              hint: 'Enter a description about yourself/company/product.',
            }
          - {
              label: Button Text,
              name: buttontext,
              widget: string,
              hint: "Enter a call to action so people can't resist to click your button.",
            }
          - {
              label: Email Address,
              name: buttonemailaddress,
              widget: string,
              pattern:
                [
                  '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$',
                  'Enter a correct email address',
                ],
              hint: 'Opens an email program after clicking on the button, that has your email address prefilled.',
            }
          - name: socialmedia
            label: Social Media
            widget: list
            fields:
              - label: 'Platform'
                name: 'platform'
                widget: 'select'
                options:
                  - { label: 'Instagram', value: 'instagram' }
                  - { label: 'Twitter', value: 'twitter' }
                  - { label: 'Facebook', value: 'facebook' }
                  - { label: 'YouTube', value: 'youtube' }
                  - { label: 'Linkedin', value: 'linkedin' }
                  - { label: 'Pinterest', value: 'pinterest' }
              - {
                  name: username,
                  label: Username,
                  widget: string,
                  hint: 'If your url is e.g. https://instagram.com/sitebuilder, than your username is sitebuilder.',
                }
          - name: searchenginedescription
            label: Description for search engines
            widget: text
            pattern: ['Ë†.{155}$', 'Description has exceeded 155 characters']
            hint: 'This text is shown in the search results of a search engine like e.g. Google or DuckDuckGo. Maximum length is 155.'
